server:
  port: 8080
  servlet:
    context-path: /demo


# Spring相关配置
spring:
  ##数据库连接信息
  datasource:
    # 数据源配置
    url: jdbc:mysql://127.0.0.1:3306/datalink?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root12345
    driver-class-name: com.mysql.jdbc.Driver

  activiti:
    # 自动建表
    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true